version: '3.9'

services: 
    db:
        container_name: first_mysql
        build:
            context: .
            dockerfile: Dockerfile.db
        ports: 
            - 3309:3306
        volumes:
            - first_go:/var/lib/mysql:rw
        environment:
            - MYSQL_USER=tonu
            - MYSQL_PASSWORD=tonu
            - MYSQL_DATABASE=first_go
            - MYSQL_ROOT_PASSWORD=tonu
        tty: true
        networks: 
            - first_networks
    first_api:
        #container_name: first_api
        build:
            context: .
        ports:
            - 8080:8080
        volumes:
            - ./:/project
        environment:
            - ENV_PATH=./config.local.json
        tty: true
        depends_on:
            - db
        networks:
            - first_networks
        restart: on-failure:3


networks:
    first_networks:
        name: first_networks
        driver: bridge
    
volumes:
    first_go:
        name: db-first-go
